spring:
  profiles:
    active: ${ACTIVE}
  config:
    import: optional:file:.env.local[.properties]
  application:
    name: mommytalk-server
  datasource:
    url: ${DB_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      default_batch_fetch_size: 100
#    properties:
#      hibernate:
#        show_sql: true # sql
#        format_sql: true # SQL
#        highlight_sql: true # SQL

line:
  secret-key: ${LINE_CHANNEL_SECRET}
  base-url: ${LINE_BASE_URL}


admin:
  header-key: ${ADMIN_HEADER_KEY}
  header-value: ${ADMIN_HEADER_VALUE}
